blog/blogproject/blogapp/urls.py
from django.urls import path
from . import views

app_name = "blogapp"

urlpatterns = [
    path("", views.home_page, name="post_list"),
    path("<int:year>/<int:month>/<int:day>/<slug:slug>", views.post_detail, name="post_detail"),
    # path("<int:num1>/<int:num2>", views.thisisit)
]

blog/blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blogapp.urls", namespace="blog"))
]

blog/blogproject/blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    
    title = models.CharField(max_length=255,)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish',)
    image = models.ImageField(upload_to='blog_images/', null=True)
    author = models.ForeignKey(User,
                                on_delete=models.CASCADE,
                                related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                                choices=STATUS_CHOICES,
                                default='draft')
    class Meta:
        ordering = ('-publish',)
        
    def __str__(self):
        return self.title
    
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={
            "year": self.publish.year,
            "month":self.publish.month,
            "day": self.publish.day,
            "slug":self.slug
        })
    


class Comment(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()
    blog_post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    date_created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('-date_created',)
        
    def __str__(self):
        return f"Comment by {self.name} on {self.blog_post.title}"

blog/blogproject/blogapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage

# from django.



def home_page(request):
    post_list = Post.objects.filter(status="published")
    
    paginator = Paginator(post_list, 3)
    
    page = request.GET.get('page', 1)
    try:
        posts = paginator.page(page)
        
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    
    progress = (posts.number/paginator.num_pages) * 100
    
    return render(request, 
                  "index.html",
                  {'posts': posts,
                   "page":page,
                   "progress": int(progress)})
    

def post_detail(request, year, month, day, slug):
    new_comment = False
    post = get_object_or_404(Post, publish__year=year, 
                             publish__month=month,
                             publish__day=day, 
                             slug=slug)
    
    all_comments = post.comments.all()
    prev_post_list = Post.objects.filter(publish__lt=post.publish)
    
    if prev_post_list.count() == 0:
        prev_post = None
    else:
        prev_post = prev_post_list.first()
        
    next_post_list = Post.objects.filter(publish__gt=post.publish)
    if next_post_list.count() == 0:
        next_post = None
    else:
        next_post = next_post_list.last()
        
        
    
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        
        Comment.objects.create(name=name, email=email, message=message, blog_post=post)
        new_comment = True
    
    return render(request,
                'single.html',
                {'post': post,
                 'prev_post':prev_post,
                 'next_post':next_post,
                 "new_comment":new_comment,
                 "all_comments":all_comments})
    

blog/blogproject/blogapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
            
            {% endblock title %}
        </title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Free Website Template" name="keywords">
        <meta content="Free Website Template" name="description">

        <!-- Favicon -->
        <link href={% static 'img/favicon.ico' %} rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:300;400;600;700;800&display=swap" rel="stylesheet">

        <!-- Font Awesome -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

        <!-- Customized Bootstrap Stylesheet -->
        <link href={% static 'css/style.css' %} rel="stylesheet">
    </head>

    <body>
        <div class="wrapper">
            <div class="sidebar">
                <div class="sidebar-text d-flex flex-column h-100 justify-content-center text-center">
                    <img class="mx-auto d-block w-75 bg-primary img-fluid rounded-circle mb-4 p-3" src="{% static 'img/profile.jpg' %}" alt="Image">
                    <h1 class="font-weight-bold">Kate Glover</h1>
                    <p class="mb-4">
                        Justo stet no accusam stet invidunt sanctus magna clita vero eirmod, sit sit labore dolores lorem. Lorem at sit dolor dolores sed diam justo
                    </p>
                    <div class="d-flex justify-content-center mb-5">
                        <a class="btn btn-outline-primary mr-2" href="#"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-primary mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-primary mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                        <a class="btn btn-outline-primary mr-2" href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                    <a href="" class="btn btn-lg btn-block btn-primary mt-auto">Hire Me</a>
                </div>
                <div class="sidebar-icon d-flex flex-column h-100 justify-content-center text-right">
                    <i class="fas fa-2x fa-angle-double-right text-primary"></i>
                </div>
            </div>
            <div class="content">
                <!-- Navbar Start -->
                {% comment %} <div class="container p-0">
                    <nav class="navbar navbar-expand-lg bg-secondary navbar-dark">
                        <a href="" class="navbar-brand d-block d-lg-none">Navigation</a>
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                            <div class="navbar-nav m-auto">
                                <a href="index.html" class="nav-item nav-link active">Home</a>
                                <a href="about.html" class="nav-item nav-link">About</a>
                                <a href="contact.html" class="nav-item nav-link">Contact</a>
                            </div>
                        </div>
                    </nav>
                </div> {% endcomment %}
                <!-- Navbar End -->
                
                {% block body %}
                
                {% endblock body %}
                
                
                
                
                <!-- Footer Start -->
                <div class="container py-4 bg-secondary text-center">
                    <p class="m-0 text-white">
                        &copy; <a class="text-white font-weight-bold" href="#">Desmond Nnebue</a>. All Rights Reserved. Designed by <a class="text-white font-weight-bold" href="#">sirdesmond</a>
                    </p>
                </div>
                <!-- Footer End -->
            </div>
        </div>
        
        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-angle-double-up"></i></a>
        
        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>

        <!-- Contact Javascript File -->
        <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
        <script src="{% static 'mail/contact.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

blog/blogproject/blogapp/templates/blog/detail.html
<h2>{{ post.title }}</h2>
<p> {{ post.body }} </p>


<p>Written by {{ post.author | capfirst }} on {{ post.publish }}</p>

blog/blogproject/blogapp/templates/blog/list.html
{% for post in posts %}
<div>
    <h3>{{ post.title }}</h3>
    <p> {{ post.body | truncatewords:10 }} <span><a href="{{ post.get_absolute_url }}">Read More</a> </span></p>
</div>
{% endfor %}

blog/blogproject/blogapp/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}

Post Lists 

{% endblock title %}

{% block body %}

    <!-- Carousel Start -->
    <div class="container p-0">
        <div id="blog-carousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="w-100" src="{% static 'img/carousel-1.jpg' %}" alt="Image">
                    <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                        <h2 class="mb-3 text-white font-weight-bold">Lorem ipsum dolor sit amet</h2>
                        <div class="d-flex text-white">
                            <small class="mr-2"><i class="fa fa-calendar-alt"></i> 01-Jan-2045</small>
                            <small class="mr-2"><i class="fa fa-folder"></i> Web Design</small>
                            <small class="mr-2"><i class="fa fa-comments"></i> 15 Comments</small>
                        </div>
                        <a href="" class="btn btn-lg btn-outline-light mt-4">Read More</a>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
                    <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                        <h2 class="text-white font-weight-bold">Lorem ipsum dolor sit amet</h2>
                        <div class="d-flex">
                            <small class="mr-2"><i class="fa fa-calendar-alt"></i> 01-Jan-2045</small>
                            <small class="mr-2"><i class="fa fa-folder"></i> Web Design</small>
                            <small class="mr-2"><i class="fa fa-comments"></i> 15 Comments</small>
                        </div>
                        <a href="" class="btn btn-lg btn-outline-light mt-4">Read More</a>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="w-100" src="{% static 'img/carousel-3.jpg' %}" alt="Image">
                    <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                        <h2 class="text-white font-weight-bold">Lorem ipsum dolor sit amet</h2>
                        <div class="d-flex">
                            <small class="mr-2"><i class="fa fa-calendar-alt"></i> 01-Jan-2045</small>
                            <small class="mr-2"><i class="fa fa-folder"></i> Web Design</small>
                            <small class="mr-2"><i class="fa fa-comments"></i> 15 Comments</small>
                        </div>
                        <a href="" class="btn btn-lg btn-outline-light mt-4">Read More</a>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#blog-carousel" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#blog-carousel" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </div>
    <!-- Carousel End -->


    <!-- Blog List Start -->
    <div class="container bg-white pt-5">
        {% for post  in posts %}

        <div class="row blog-item px-3 pb-5">
            <div class="col-md-5">
                <img class="img-fluid mb-4 mb-md-0" src={{ post.image.url }} alt="Image">
            </div>
            <div class="col-md-7">
                <h3 class="mt-md-4 px-md-3 mb-2 py-2 bg-white font-weight-bold"> {{ post.title }}</h3>
                <div class="d-flex mb-3">
                    <small class="mr-2 text-muted"><i class="fa fa-calendar-alt"></i> {{ post.publish }} </small>
                    
                    <small class="mr-2 text-muted"><i class="fa fa-comments"></i> 15 Comments</small>
                </div>
                <p>
                    {{ post.body | truncatewords:15 }}
                </p>
                <a class="btn btn-link p-0" href="{{ post.get_absolute_url }}">Read More <i class="fa fa-angle-right"></i></a>
            </div>
        </div>

        {% endfor %}
    </div>
    <!-- Blog List End -->
    
    <!-- Pagination-->
    <div class="col-md-12 pt-4">
        <div class="d-flex flex-column skills">
            <div class="progress w-100 mb-4">
                <div class="progress-bar" role="progressbar" aria-valuenow="{{progress}}" aria-valuemin="{{ posts.number }}" aria-valuemax="{{ posts.paginator.num_pages }}">{{ posts.number }} of {{ posts.paginator.num_pages }} </div>
            </div>
        </div>
    </div>
    <div class="col-12 py-4">
        <div class="btn-group btn-group-lg w-100">
            {% if posts.has_previous %}
    
            <a href="?page={{ posts.previous_page_number }}" class="btn btn-sm btn-outline-primary mb-1">Previous</a>

            {% endif %}
            
            {% if posts.has_next %}

            <a href="?page={{ posts.next_page_number }}" class="btn btn-sm btn-outline-primary mb-1">Next</a>

            {% endif %}
        </div> 
    </div>
    <!-- Pagination ends-->




    <!-- Subscribe Start -->
    <div class="container py-5 px-4 bg-secondary text-center">
        <h1 class="text-white font-weight-bold">Subscribe My Newsletter</h1>
        <p class="text-white">Subscribe and get my latest article in your inbox</p>
        <form class="form-inline justify-content-center">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Your Email">
                <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Subscribe</button>
                </div>
            </div>
        </form>
    </div>
    <!-- Subscribe End -->

{% endblock body %}

blog/blogproject/blogapp/templates/single.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ post.title }}
{% endblock title %}


{% block body %}


{% if new_comment %}
    <div class="popup">
        <span class="popuptext" id="myPopup">Added Comment</span>
    </div>

{% endif %}


<!-- Page Header Start -->
<div class="container py-5 px-2 bg-primary">
    <div class="row py-5 px-4">
        <div class="col-sm-6 text-center text-md-left">
            <h1 class="mb-3 mb-md-0 text-white text-uppercase font-weight-bold">{{ post.title }}</h1>
        </div>
        <div class="col-sm-6 text-center text-md-right">
            <div class="d-inline-flex pt-2">
                <h4 class="m-0 text-white"><a class="text-white" href="{% url 'blog:post_list' %}">Home</a></h4>
                <h4 class="m-0 text-white px-2">/</h4>
                <h4 class="m-0 text-white">Blog Detail</h4>
            </div>
        </div>
    </div>
</div>
<!-- Page Header End -->

<!-- Blog Detail Start -->
<div class="container py-5 px-2 bg-white">
    <div class="row px-4">
        <div class="col-12">
            <img class="img-fluid mb-4" src={{ post.image.url }} alt= {{ post.title | title }}>
            <h2 class="mb-3 font-weight-bold"> {{ post.title | title }} </h2>
            <div class="d-flex">
                <p class="mr-3 text-muted"><i class="fa fa-calendar-alt"></i> {{post.publish }} </p>
                <p class="mr-3 text-muted"><i class="fa fa-comments"></i> 15 Comments</p>
            </div>
            <p style="text-align:justify;">{{ post.body }}</p>
        </div>

        {% comment %} <div class="col-12 py-4">
            <a href="" class="btn btn-sm btn-outline-primary mb-1">Lorem</a>
            <a href="" class="btn btn-sm btn-outline-primary mb-1">Lorem</a>
            <a href="" class="btn btn-sm btn-outline-primary mb-1">Lorem</a>
            <a href="" class="btn btn-sm btn-outline-primary mb-1">Lorem</a>
            <a href="" class="btn btn-sm btn-outline-primary mb-1">Lorem</a>
            <a href="" class="btn btn-sm btn-outline-primary mb-1">Lorem</a>
            <a href="" class="btn btn-sm btn-outline-primary mb-1">Lorem</a>
        </div> {% endcomment %}

        <div class="col-12 py-4">
            <div class="btn-group btn-group-lg w-100">
                {% if prev_post %}
        
                <a href="{{ prev_post.get_absolute_url }}" class="btn btn-sm btn-outline-primary mb-1">Previous</a>

                {% endif %}
                
                {% if next_post %}

                <a href="{{ next_post.get_absolute_url }}" class="btn btn-sm btn-outline-primary mb-1">Next</a>

                {% endif %}
            </div> 
        </div>
        <div class="col-12 py-4">
            {% with all_comments.count as total_comments %}
            <h3 class="mb-4 font-weight-bold">{{ total_comments }} Comment{{ total_comments|pluralize }}</h3>
            {% endwith %}
            
            {% for comment in all_comments %}
            <div class="media mb-4">
                <div class="media-body">
                    <h4>{{ comment.name}} <small><i> {{ comment.date_created }} </i></small></h4>
                    <p>{{ comment.message}}
                    </p>
                </div>
            </div>
            {% endfor %}
            
        </div>
        <div class="col-12">
            <h3 class="mb-4 font-weight-bold">Leave a comment</h3>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Name *</label>
                    <input type="text" class="form-control" id="name" required name="name">
                </div>
                <div class="form-group">
                    <label for="email">Email *</label>
                    <input type="email" class="form-control" id="email" required name="email">
                </div>

                <div class="form-group">
                    <label for="message">Message *</label>
                    <textarea id="message" cols="30" rows="5" class="form-control" required name="message"></textarea>
                </div>
                <div class="form-group">
                    <input type="submit" value="Leave Comment" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Blog Detail End -->



{% endblock body %}